name: NGINX Config Generator

on:
  push:
    branches:
      - main # Измените на вашу основную ветку, если необходимо
    paths:
      - 'input_files/**' # Путь к директории, где будут храниться входные файлы

jobs:
  generate_nginx_config:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка кода
        uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Укажите нужную версию Python
      - name: Запуск скрипта генерации конфигурации NGINX
        run: |
          # Получаем имя файла и формируем имя выходного файла
          input_file=$(git diff --name-only HEAD^ HEAD | grep 'input_files/' | head -n 1)
          server_name="expert-fintarget-k8s.mybroker.global.bcs" # Замените на ваше значение
          current_date=$(date +'%Y-%m-%d')
          output_file="nginx_config_${current_date}_${server_name}.conf"

          # Запуск скрипта с параметрами
          python generate_nginx_config.py "$input_file" "$output_file"

      - name: Загрузка сгенерированного файла
        uses: actions/upload-artifact@v3
        with:
          name: nginx-config
          path: nginx_config_*.conf
